### ISSUE TITLE
Ctrl-C / SIGINT handling on Windows

### ISSUE THREAD

**Issue by bmeurant** [ember-cli/ember-cli#5236]
Hi,

I use to run ember-cli on Windows and I to use npm script to run ``ember server``, setting default options for the team (like `` --proxy``).

Because of this script usage, we have some troubles with SIGINT handling : the prompt ``Terminate batch job (Y/N)?`` is always shown after ``Ctrl+C``. Obviously, it has no effect and often causes painful shell crashes.

I found that the monitoctrlc lib (https://www.npmjs.com/package/monitorctrlc) could be used to resolve this issue. Unfortunately, I did not found anything to hook the activation of this lib before ``ember server``.

Do you think it could be possible to integrate this lib (or equivalent) or to provide a way to integrate it ourselves ?

**Comment by stefanpenner** [comment]
So you would prefer to disable the default windows batch job handling?

**Comment by felixrieseberg** [comment]
Yeah, catching SIGINT is a good idea. We don't have to disable batch handling, we just have to make sure that we just terminate the whole thing on CTRL + C. It's a good idea.

`monitorctrlc` seems simple enough - it just watches for CTRL + C, and if invoked, terminates the process. I can take a look at the code base next week to find a spot to sneak it in ;-)

**Comment by bmeurant** [comment]
Hi,

Indeed, I was not thinking to disable the whole default windows batch handling, only intercepting CTRL-C for this specific process and ending it properly ...

@felixrieseberg big thanks to you. It will be awesome if you could take this look ;-)

**Comment by rwjblue** [comment]
We listen for `SIGINT` here: https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L81

**Comment by felixrieseberg** [comment]
The trouble is that the Windows prompt will show up before SIGINT is even sent - PR #5238 adds a small check that should fix this issue, using the SIGINT callback @rwjblue mentioned above.

**Comment by bmeurant** [comment]
@felixrieseberg awesome ! It seems working like a charm.

Working directly with ``ember server`` or enclosed inside an ``npm start`` script, no more prompt and, mainly, no shell crashes anymore !! Many thanks.

However, I still have a kind of issue running ``npm start`` script enclosing ``ember server`` : The ``server`` process exits whit an error flag `1`, in case of SIGINT, SIGTERM or kill (here: https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L212). This causes npm to log an error stack.

@rwjblue is there some cases where SIGINT, SIGTERM or kill really need to be reported as errors by exiting `1`? I mean, If the user asked to exit, it is not an error and, if due to shell or system crash, the reported error, if it can ever be seen by the user, does not provide any useful information IMO. Besides, exiting(0) in that kind of case does not seem to be a bad practice according to npm doc (https://docs.npmjs.com/misc/scripts#best-practices)

But maybe, I am missing something. Let me know.

Thanks anyway. Love opensource ;-)

**Comment by stefanpenner** [comment]
closing infavor of PR
